export enum ServiceKey {
    CONFIG_GAME = "CONFIG",
    EVENT_MANAGER = "EVENT_MANAGER",
    POOL_FACTORY = "POOL_FACTORY",
    SOUND_MANANGER = "SOUND_MANANGER",
    GUI_MANAGER = "GUI_MANAGER",
    BATTLE_MANAGER = "BATTLE_MANAGER",
}